### PR TITLE
Convert to Playwright 1: Install Playwright and convert forward/back test

### PR DESCRIPTION
**Pull request by 6notes**
# Summary
This PR addresses #306 by installing Playwright and converts the Cypress forward/back test into a Playwright test.

# Details
- I wasn't able to find any good `exists` checks in Playwright; I think the equivalent is `toBeVisible/isVisible`. According to [Playwright's docs](https://playwright.dev/docs/actionability#visible), being visible means that "it has [a] non-empty bounding box and does not have [the] visibility:hidden computed style."
- Specific Playwright tests can be run like so: `npx playwright test browser-nav.spec.ts`

<details>
<summary>

# Stacked PRs in this series

</summary>

- lizadaly/windrift#312
- 6notes/windrift#1
- 6notes/windrift#2
- 6notes/windrift#3
- 6notes/windrift#4
- 6notes/windrift#5
- 6notes/windrift#6
- 6notes/windrift#7
- 6notes/windrift#8
- 6notes/windrift#9

</details>

### CODE REVIEW

**Comment by lizadaly** [comment]
Wow, thank you for working on this! Let me know if you have any questions or would like a hand (or when you’d like a review).

**Comment by 6notes** [comment]
Hi @lizadaly, here are some questions I have:
- In my 9th stacked PR, I installed `lodash` to fix an module import error when running end to end tests. Is it worth doing separate lodash installs instead where we only install the required function?
- Currently all of the stacked PRs after the first one have their bases set to the previous PR in my forked repo, should I base these on the main branch in your repo instead?

Otherwise, I think my PRs are ready for review, please let me know if I can do anything to make the PRs easier to review, or if videos of the end to end tests would be helpful. : )

If you would like to see the tests for yourself, you can run `npx playwright test browser-nav.spec.ts --debug` and jump through step by step.

**Comment by 6notes** [comment]
I've left the `lodash` imports as is.

> My slight preference would be to squash the 10 and then open a new PR against `main`

I've opened #313 against `main`.

**Comment by 6notes** [comment]
Closing this in favor of #313 .

**Pull request closed without merging**
